### ISSUE TITLE
Packing zray plugin... deployment.xml not found

### ISSUE THREAD

**Issue by christophermancini** [zend-server-plugins/Documentation#7]
So, I the documentation doesn't specify the process of making a plugin zpk. It specifies using a deployment.json, but the zdpack tool requires an xml file. Is there a different tool I should be using or parameters for zdpack?

**Comment by idangozlan** [comment]
Hi,

You are right, zdpack tool is for packing applications.
To pack plugin, please compress it as regular zip file and change the ext. to zpk.

Thanks!
